export const CHANGE_IMAGE_URL_INPUT_FIELD = 'CHANGE_IMAGE_URL_FIELD';

export const DETECT_IMAGE_CLICK = 'DETECT_IMAGE_CLICK';
export const CHANGE_CURRENT_IMAGE_SIZE = 'CHANGE_CURRENT_IMAGE_SIZE';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';

export const SIGN_IN_USER_PENDING = 'SIGN_IN_USER_PENDING';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAIL = 'SIGN_IN_USER_FAIL';

export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_ERROR';

export const UPDATE_USER_RANK_PENDING = 'UPDATE_USER_RANK_PENDING';
export const UPDATE_USER_RANK_SUCCESS = 'UPDATE_USER_RANK_SUCCESS';
export const UPDATE_USER_RANK_FAIL = 'UPDATE_USER_RANK_ERROR';

export const REQUEST_FACE_DETECTION_PENDING = 'REQUEST_FACE_DETECTION_PENDING';
export const REQUEST_FACE_DETECTION_SUCCESS = 'REQUEST_FACE_DETECTION_SUCCESS';
export const REQUEST_FACE_DETECTION_ERROR = 'REQUEST_FACE_DETECTION_ERROR';